name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Build Docker image
      run: |
        docker build -t my-springboot-app .

    - name: Run Docker container
      run: |
        docker run -d --rm -p 8080:8080 my-springboot-app
        
        
  test:
    runs-on: ubuntu-latest
    if: false  # This condition ensures the job is never executed
    steps:
      - name: Skip this job
        run: echo "This job is skipped"
